var topics =
[
    [ "Cortex-M4 Core Peripherals", "group__cortex__m4__core.html", "group__cortex__m4__core" ],
    [ "STM32F401RE Hardware Abstraction Layer", "group__stm32f401re__hal.html", "group__stm32f401re__hal" ],
    [ "STM32F401RE GPIO Driver", "group__stm32__gpio.html", "group__stm32__gpio" ],
    [ "STM32F401RE I2C Driver", "group__stm32__i2c.html", "group__stm32__i2c" ],
    [ "STM32F401RE RCC Driver", "group__stm32__rcc.html", "group__stm32__rcc" ],
    [ "STM32F401RE RTC Driver", "group__stm32__rtc.html", "group__stm32__rtc" ],
    [ "STM32F401RE SPI Driver", "group__stm32__spi.html", "group__stm32__spi" ],
    [ "STM32F401RE USART Driver", "group__stm32__usart.html", "group__stm32__usart" ],
    [ "Cortex-M4 NVIC Public APIs", "group__cortex__m4__nvic__public__apis.html", "group__cortex__m4__nvic__public__apis" ],
    [ "SysTick Public APIs", "group__cortex__m4__systick__public__apis.html", "group__cortex__m4__systick__public__apis" ],
    [ "GPIO Public APIs", "group__stm32__gpio__public__apis.html", "group__stm32__gpio__public__apis" ],
    [ "GPIO Internal Helpers", "group__stm32__gpio__internal__helpers.html", "group__stm32__gpio__internal__helpers" ],
    [ "I2C Public APIs", "group__stm32__i2c__public__apis.html", "group__stm32__i2c__public__apis" ],
    [ "I2C Internal Helpers", "group__stm32__i2c__internal__helpers.html", "group__stm32__i2c__internal__helpers" ],
    [ "RCC Public APIs", "group__stm32__rcc__public__apis.html", "group__stm32__rcc__public__apis" ],
    [ "RTC Public APIs", "group__stm32__rtc__public__apis.html", "group__stm32__rtc__public__apis" ],
    [ "RTC Internal Helpers", "group__stm32__rtc__internal__helpers.html", "group__stm32__rtc__internal__helpers" ],
    [ "SPI Public APIs", "group__stm32__spi__public__apis.html", "group__stm32__spi__public__apis" ],
    [ "SPI Internal Helpers", "group__stm32__spi__internal__helpers.html", "group__stm32__spi__internal__helpers" ],
    [ "USART Public APIs", "group__stm32__usart__public__apis.html", "group__stm32__usart__public__apis" ],
    [ "USART Internal Helpers", "group__stm32__usart__internal__helpers.html", "group__stm32__usart__internal__helpers" ],
    [ "Button Module", "group__BUTTON__MODULE.html", "group__BUTTON__MODULE" ],
    [ "Circular Buffer Module", "group__cbuf__module.html", "group__cbuf__module" ],
    [ "Command Module", "group__cmd__module.html", "group__cmd__module" ],
    [ "Common Utility Module", "group__common__module.html", "group__common__module" ],
    [ "Console Module", "group__console__module.html", "group__console__module" ],
    [ "Data Log Module", "group__datalog__module.html", "group__datalog__module" ],
    [ "Error Codes", "group__err__module.html", "group__err__module" ],
    [ "Initialization Module", "group__init__module.html", "group__init__module" ],
    [ "IO Module", "group__io__module.html", "group__io__module" ],
    [ "Log Module", "group__log__module.html", "group__log__module" ],
    [ "Menu Module", "group__menu__module.html", "group__menu__module" ],
    [ "Module Identifiers", "group__modules__module.html", "group__modules__module" ],
    [ "NEO-6 GPS Module", "group__neo6__module.html", "group__neo6__module" ],
    [ "SD Card Module", "group__sd__module.html", "group__sd__module" ],
    [ "SSD1309 Display Module", "group__ssd1309__module.html", "group__ssd1309__module" ],
    [ "Button Public APIs", "group__BUTTON__Public__APIs.html", "group__BUTTON__Public__APIs" ],
    [ "Button Command Handlers", "group__BUTTON__COMMAND__HANDLERS.html", "group__BUTTON__COMMAND__HANDLERS" ],
    [ "Circular Buffer Public APIs", "group__cbuf__public__apis.html", "group__cbuf__public__apis" ],
    [ "Command Public APIs", "group__cmd__public__apis.html", "group__cmd__public__apis" ],
    [ "Common Public APIs", "group__common__public__apis.html", "group__common__public__apis" ],
    [ "Console Public APIs", "group__console__public__apis.html", "group__console__public__apis" ],
    [ "Data Log Public APIs", "group__datalog__public__apis.html", "group__datalog__public__apis" ],
    [ "Data Log Command Handlers", "group__datalog__command__handlers.html", "group__datalog__command__handlers" ],
    [ "Initialization Public APIs", "group__init__public__apis.html", "group__init__public__apis" ],
    [ "IO Public APIs", "group__io__public__apis.html", "group__io__public__apis" ],
    [ "IO Command Handlers", "group__io__command__handlers.html", "group__io__command__handlers" ],
    [ "Log Public APIs", "group__log__public__apis.html", "group__log__public__apis" ],
    [ "Log Internal Helpers", "group__log__internal__helpers.html", "group__log__internal__helpers" ],
    [ "Menu Public APIs", "group__menu__public__apis.html", "group__menu__public__apis" ],
    [ "Menu Internal Helpers", "group__menu__internal__helpers.html", "group__menu__internal__helpers" ],
    [ "Menu Command Handlers", "group__menu__command__handlers.html", "group__menu__command__handlers" ],
    [ "NEO-6 Public APIs", "group__neo6__public__apis.html", "group__neo6__public__apis" ],
    [ "NEO-6 Internal Helpers", "group__neo6__internal__helpers.html", "group__neo6__internal__helpers" ],
    [ "NEO-6 Command Handlers", "group__neo6__command__handlers.html", "group__neo6__command__handlers" ],
    [ "SD Card Public APIs", "group__sd__public__apis.html", "group__sd__public__apis" ],
    [ "SD Internal Helpers", "group__sd__internal__helpers.html", "group__sd__internal__helpers" ],
    [ "SD Command Handlers", "group__sd__command__handlers.html", "group__sd__command__handlers" ],
    [ "SSD1309 Public APIs", "group__ssd1309__public__apis.html", "group__ssd1309__public__apis" ],
    [ "SSD1309 Command Handlers", "group__ssd1309__command__handlers.html", "group__ssd1309__command__handlers" ]
];