/**
 * @file err.h
 * @author github.com/Baksi675
 * @brief Header file containing error codes
 * @version 0.1
 * @date 2026-01-22
 * 
 * @copyright Copyright (c) 2026
 * 
 */

#ifndef ERR_H_
#define ERR_H_

typedef enum {
	ERR_OK,
	ERR_UNKNOWN,
	ERR_INVALID_ARGUMENT,
	ERR_INVALID_POINTER,
	ERR_INVALID_CONFIGURATION,
	ERR_ARRAY_OUT_OF_BOUNDS,
	ERR_UNINITIALZIED_OBJECT,
	ERR_INITIALIZATION_FAILURE,
	ERR_DEINITIALIZATION_FAILURE,
	ERR_CATASTROPHIC_FAILURE,
	ERR_DATA_COPY_FAILURE,
	ERR_DATA_ACQUISITION_FAILURE,
	ERR_BUFFER_FULL,
	ERR_NOT_ENOUGH_SPACE,
	ERR_ILLEGAL_ACTION,
	ERR_UNSUCCESFUL_ACTION,
	ERR_TIMEOUT,
	ERR_UNRECOGNIZED_HW
}ERR_te;

#endif