/**
 * @file stm32f401re_spi.h
 * @author github.com/Baksi675
 * @brief STM32F401RE SPI driver public API.
 *
 * @details
 * This module provides a blocking full-duplex SPI driver for the STM32F401RE,
 * supporting master and slave modes, 8-bit and 16-bit data frames, hardware
 * and software slave select, and all four SPI clock modes (CPOL/CPHA).
 *
 * All transfer functions are blocking — they poll status flags and return
 * only after the transfer completes. Peripheral clock management is handled
 * internally.
 *
 * The driver separates peripheral configuration from bus enablement:
 * - @ref spi_init configures the peripheral registers but does not enable it.
 * - @ref spi_set_comm enables (SPE = 1) or disables (waits for BSY, then SPE = 0)
 *   the peripheral, controlling bus ownership.
 *
 * Typical usage:
 * - Populate an @ref SPI_CFG_ts and call @ref spi_init
 * - Call @ref spi_set_comm with @ref ENABLE before the first transfer
 * - Call @ref spi_send and/or @ref spi_receive
 * - Call @ref spi_set_comm with @ref DISABLE after the last transfer
 *
 * @version 0.1
 * @date 2026-01-30
 *
 * @copyright Copyright (c) 2026
 *
 */

/**
 * @defgroup stm32_spi STM32F401RE SPI Driver
 * @brief Blocking full-duplex SPI driver for the STM32F401RE.
 * @{
 */

#ifndef STM32F401RE_SPI_DRIVER_H__
#define STM32F401RE_SPI_DRIVER_H__

#include "stm32f401re.h"
#include "common.h"

/**
 * @defgroup stm32_spi_types SPI Types
 * @ingroup stm32_spi
 * @brief Configuration enumerations and structures for the SPI driver.
 * @{
 */

/**
 * @brief SPI operating mode.
 */
typedef enum {
    SPI_MODE_SLAVE,  /**< Slave mode: SCLK is driven by the external master. */
    SPI_MODE_MASTER  /**< Master mode: SCLK is generated by this peripheral. */
} SPI_MODE_te;

/**
 * @brief SPI data frame size.
 *
 * @note The enumerator name `SPI_DATA_FRAME_FORMATE_8_BIT` contains a typo
 *       ("FORMATE") carried from the original implementation.
 */
typedef enum {
    SPI_DATA_FRAME_FORMATE_8_BIT,  /**< 8-bit data frame. */
    SPI_DATA_FRAME_FORMAT_16_BIT   /**< 16-bit data frame. */
} SPI_DATA_FRAME_FORMAT_te;

/**
 * @brief SPI clock polarity (CPOL).
 *
 * @details
 * Determines the idle state of the SCLK line between transfers.
 */
typedef enum {
    SPI_CLOCK_POLARITY_0_IDLE, /**< CPOL = 0: SCLK is LOW when idle. */
    SPI_CLOCK_POLARITY_1_IDLE  /**< CPOL = 1: SCLK is HIGH when idle. */
} SPI_CLOCK_POLARITY_te;

/**
 * @brief SPI clock phase (CPHA).
 *
 * @details
 * Determines which clock edge is used to sample and drive data.
 */
typedef enum {
    SPI_CLOCK_PHASE_FIRST_TRANSITION,  /**< CPHA = 0: data captured on the first clock edge. */
    SPI_CLOCK_PHASE_SECOND_TRANSITION  /**< CPHA = 1: data captured on the second clock edge. */
} SPI_CLOCK_PHASE_te;

/**
 * @brief SPI frame bit order.
 */
typedef enum {
    SPI_BIT_FIRST_MSB, /**< MSB transmitted first (standard). */
    SPI_BIT_FIRST_LSB  /**< LSB transmitted first. */
} SPI_BIT_FIRST_te;

/**
 * @brief SPI slave select (NSS) management mode.
 */
typedef enum {
    SPI_SLAVE_SELECT_MODE_HW, /**< Hardware NSS: managed automatically by the peripheral. */
    SPI_SLAVE_SELECT_MODE_SW  /**< Software NSS: managed manually by the application via GPIO. */
} SPI_SLAVE_SELECT_MODE_te;

/**
 * @brief SPI master clock speed as a division of the peripheral clock (PCLK).
 *
 * @details
 * Only relevant in master mode (@ref SPI_MODE_MASTER). The actual SCK
 * frequency is PCLK / divisor, where PCLK is APB2 for SPI1/SPI4 and
 * APB1 for SPI2/SPI3.
 */
typedef enum {
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_2,   /**< SCK = PCLK / 2.   */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_4,   /**< SCK = PCLK / 4.   */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_8,   /**< SCK = PCLK / 8.   */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_16,  /**< SCK = PCLK / 16.  */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_32,  /**< SCK = PCLK / 32.  */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_64,  /**< SCK = PCLK / 64.  */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_128, /**< SCK = PCLK / 128. */
    SPI_MASTER_SCLK_SPEED_PCLK_DIV_256  /**< SCK = PCLK / 256. */
} SPI_MASTER_SCLK_SPEED_te;

/**
 * @brief Configuration structure for initializing an SPI peripheral.
 *
 * @details
 * Passed to @ref spi_init. It is recommended to zero-initialize this
 * structure before use. Fields that are irrelevant for the selected
 * mode are ignored:
 * - @ref master_sclk_speed is only used in @ref SPI_MODE_MASTER.
 */
typedef struct {
    /** Pointer to the SPI peripheral instance (SPI1–SPI4). */
    SPI_REGDEF_ts *instance;

    /** Operating mode: master or slave. */
    SPI_MODE_te mode;

    /** Data frame size: 8-bit or 16-bit. */
    SPI_DATA_FRAME_FORMAT_te data_frame_format;

    /** SCLK idle polarity (CPOL). */
    SPI_CLOCK_POLARITY_te clock_polarity;

    /** Data capture edge (CPHA). */
    SPI_CLOCK_PHASE_te clock_phase;

    /** Bit transmission order (MSB or LSB first). */
    SPI_BIT_FIRST_te bit_first;

    /** NSS (slave select) management mode: hardware or software. */
    SPI_SLAVE_SELECT_MODE_te slave_select_mode;

    /** Master SCK speed as a PCLK divisor. Only used in master mode. */
    SPI_MASTER_SCLK_SPEED_te master_sclk_speed;
} SPI_CFG_ts;

/** @} */

/**
 * @defgroup stm32_spi_api SPI Public API
 * @ingroup stm32_spi
 * @brief Public functions to interact with the SPI peripheral.
 * @{
 */

/**
 * @brief Initializes the SPI peripheral with the given configuration.
 *
 * @details
 * Enables the peripheral clock and configures data frame format, clock
 * polarity, clock phase, bit order, slave select mode, master/slave mode,
 * and (in master mode) the SCK speed. Does not enable the peripheral for
 * communication; call @ref spi_set_comm with @ref ENABLE to do so.
 *
 * Default values if fields are zero-initialized:
 * - Mode: slave
 * - Data frame: 8-bit
 * - Clock polarity: idle low (CPOL = 0)
 * - Clock phase: first transition (CPHA = 0)
 * - Bit order: MSB first
 * - Slave select: hardware
 * - Master speed: PCLK / 2
 *
 * @param[in] spi_cfg Pointer to the SPI configuration structure.
 *
 * @note It is recommended to zero-initialize @ref SPI_CFG_ts before use.
 */
void spi_init(SPI_CFG_ts *spi_cfg);

/**
 * @brief Deinitializes the SPI peripheral and disables its clock.
 *
 * @details
 * Triggers an RCC peripheral reset for the given instance and then
 * disables the peripheral clock.
 *
 * @param[in] spi_instance Pointer to the SPI instance to deinitialize.
 */
void spi_deinit(SPI_REGDEF_ts const *spi_instance);

/**
 * @brief Blocking SPI transmit. Sends @p len bytes from @p tx_buffer.
 *
 * @details
 * Transmits data one frame at a time, polling TXE before each write and
 * RXNE after each write to drain the receive FIFO (required in full-duplex
 * mode to prevent overrun). Supports both 8-bit and 16-bit frame formats.
 *
 * @param[in] spi_instance Pointer to the SPI peripheral instance.
 * @param[in] tx_buffer    Pointer to the transmit data buffer.
 * @param[in] len          Number of bytes to transmit. Must be even for 16-bit frames.
 *
 * @note The peripheral must be enabled via @ref spi_set_comm before calling
 *       this function.
 */
void spi_send(SPI_REGDEF_ts *spi_instance, uint8_t *tx_buffer, uint32_t len);

/**
 * @brief Blocking SPI receive. Reads @p len bytes into @p rx_buffer.
 *
 * @details
 * Receives data by transmitting dummy bytes (0xFF) to generate the SCK
 * clock signal, then reads the received byte from the data register.
 * Supports both 8-bit and 16-bit frame formats.
 *
 * @param[in]  spi_instance Pointer to the SPI peripheral instance.
 * @param[out] rx_buffer    Pointer to the receive data buffer.
 * @param[in]  len          Number of bytes to receive. Must be even for 16-bit frames.
 *
 * @note The peripheral must be enabled via @ref spi_set_comm before calling
 *       this function.
 */
void spi_receive(SPI_REGDEF_ts *spi_instance, uint8_t *rx_buffer, uint32_t len);

/**
 * @brief Changes the SPI master clock speed divisor at runtime.
 *
 * @details
 * Updates the BR field in SPI_CR1 without a full re-initialization.
 * Used by the SD card driver to ramp the SCK from the slow initialization
 * speed (100–400 kHz) to the maximum speed after card initialization.
 *
 * @param[in] spi_instance Pointer to the SPI peripheral instance.
 * @param[in] pclk_div     The new clock divisor to apply.
 *
 * @note The peripheral should be disabled (SPE = 0) before changing BR.
 *       In practice this is called between transactions so the peripheral
 *       is idle, but be cautious if calling mid-transaction.
 */
void spi_set_pclk_div(SPI_REGDEF_ts *spi_instance, SPI_MASTER_SCLK_SPEED_te pclk_div);

/**
 * @brief Enables or disables the SPI peripheral (SPE bit).
 *
 * @details
 * - **ENABLE**: sets SPE, activating the peripheral for communication.
 *   Must be called before the first @ref spi_send or @ref spi_receive.
 * - **DISABLE**: waits for the BSY flag to clear (transfer complete),
 *   then clears SPE. Must be called after the last transfer.
 *
 * @param[in] spi_instance Pointer to the SPI peripheral instance.
 * @param[in] en_status    @ref ENABLE to activate, @ref DISABLE to deactivate.
 */
void spi_set_comm(SPI_REGDEF_ts *spi_instance, EN_STATUS_te en_status);

/** @} */

#endif

/** @} */